# Generated by Django 5.1.5 on 2025-04-18 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=100)),
                ('father_name', models.CharField(max_length=100)),
                ('mother_name', models.CharField(max_length=100)),
                ('birth_date', models.DateField()),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=6)),
                ('present_address', models.TextField()),
                ('nationality', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=20)),
                ('email_address', models.EmailField(max_length=254)),
                ('occupation', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('Single', 'Single'), ('Married', 'Married')], max_length=10)),
                ('course_name', models.CharField(max_length=100)),
                ('photo', models.ImageField(upload_to='photos/')),
                ('signature', models.ImageField(upload_to='signatures/')),
            ],
        ),
    ]
